### PR TITLE
Updated elisaviihde.py to be python3 compatible

### PR DESCRIPTION
**Pull request by Tomin1**
Updated elisaviihde.py to be python3 compatible. The code is still compatible
with python2.

Replaces #15.

### CODE REVIEW

**Comment by enyone** [comment]
With what version of python3 was this tested? (just to add it to TravisCI and  README.md)

**Comment by Tomin1** [comment]
I used 3.5.1 on my laptop, but I think it should work with any 3.x version.

**Comment by enyone** [comment]
Nose tests didn't like 3.5 :( Seems to be a problem in **requests** module. Any ideas?
https://travis-ci.org/enyone/elisaviihde/jobs/96555689

**Comment by Tomin1** [comment]
Well, it's obvious I didn't do any unit tests, just some smoke testing with my own scripts and there it seemed to work. Anyway it seems that testing code (httmock) does something differently than the real api. I'm not very familiar with httmock. It looks like there is (or was) some code on httmock to prevent this but there might be some bugs left.
httmock unit test: https://github.com/patrys/httmock/blob/master/tests.py#L222

You might want to use 3.4 as that is the latest requests and httmock really support. I used that version of oython (3.4.3) on my server probably did equal amount of testing elisaviihde.py on it (compared to testing done with 3.5.1 on my laptop). Anyway, the unit tests aren't going to work on 3.4 either.

**Comment by enyone** [comment]
Python community has ruined itself making things not being backward compatible. I will mark Python3 support as experimental as long as unit tests are fixed.

**Comment by enyone** [comment]
Opened bug https://github.com/enyone/elisaviihde/issues/17

**Pull request merged**
